### ISSUE TITLE
Alias 'h' used twice in initial installation

### ISSUE THREAD

**Issue by axelknauf** [matthewwoodruff/sdoc#3]
After initial installation the basic instructions say that the alias 'h' can be used to print "hello world". Instead it is also used for the "help" built-in command, which takes precedence. 

Suggestion: Use a different alias for "hello world".

**Comment by matthewwoodruff** [comment]
Hey Axel, thanks for the feedback. I've changed the alias for the hello world command to `hw`. See the linked commit for more info.
